# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-23 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='img',
            field=models.ImageField(upload_to='%Y%m/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='effective_or_not'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='img_name'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modify_time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='effective_end_time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='top_or_not'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='delete_or_not'),
        ),
        migrations.AlterField(
            model_name='news',
            name='reorder',
            field=models.SmallIntegerField(default=0, help_text='数字越大，越靠前', verbose_name='sort'),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='effective_start_time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='types',
            field=models.SmallIntegerField(choices=[(11, '新闻'), (12, '通知')], default=11, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modify_time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='view_count'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='effective_end_time'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(upload_to='slider', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='delete_or_not'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='reorder',
            field=models.SmallIntegerField(default=0, help_text='数字越大，越靠前', verbose_name='sort'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='effective_start_time'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='target_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='target_url'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='types',
            field=models.SmallIntegerField(choices=[(11, '首页')], default=11, verbose_name='show_position'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modify_time'),
        ),
    ]
