# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200523_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify_time'),
        ),
    ]
