# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-27 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200527_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='img',
            field=models.ImageField(upload_to='%Y%m/images/', verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='valid or not'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='image name'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Effective end time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Whether to stick'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='valid or not'),
        ),
        migrations.AlterField(
            model_name='news',
            name='reorder',
            field=models.SmallIntegerField(default=0, help_text='The higher the number, the higher the front', verbose_name='reorder'),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Effective start time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='views time'),
        ),
    ]
