# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-30 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200527_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
