# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-27 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
