# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-23 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20200523_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
