# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-27 08:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20190506_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classify',
            options={'ordering': ['-reorder'], 'verbose_name': 'goods_classification', 'verbose_name_plural': 'goods_classification'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-reorder'], 'verbose_name': 'product information', 'verbose_name_plural': 'product information'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-reorder'], 'verbose_name': 'product tags', 'verbose_name_plural': 'product tags'},
        ),
        migrations.AlterField(
            model_name='classify',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='desc',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='img',
            field=models.ImageField(upload_to='classify', verbose_name='classify_image'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='is_valid'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='name',
            field=models.CharField(max_length=12, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='reorder',
            field=models.SmallIntegerField(default=0, verbose_name='reorder'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='classify_ID'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Purchase link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes', to='mall.Classify', verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='product details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='%Y%m/product', verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='is_valid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_price',
            field=models.FloatField(verbose_name='original price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Exchange price (point exchange)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ramain_count',
            field=models.IntegerField(default=0, verbose_name='Remaining stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder',
            field=models.SmallIntegerField(default=0, verbose_name='reorder'),
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.FloatField(default=10.0, verbose_name='product rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_count',
            field=models.IntegerField(default=0, verbose_name='in stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(11, 'on sale'), (12, 'sold out'), (13, 'removed')], default=12, verbose_name='Commodity status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='mall.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.SmallIntegerField(choices=[(11, 'Physical goods'), (12, 'virtual merchandise')], default=11, verbose_name='product type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='product_id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='view count'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tags', verbose_name='main_image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='is_valid'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=12, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='reorder',
            field=models.SmallIntegerField(default=0, verbose_name='reorder'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='tag_id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modify_time'),
        ),
    ]
