# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-30 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20200527_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
    ]
