# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-23 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.FloatField(verbose_name='total_price'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(verbose_name='purchase_amount'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='product_main_image'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=128, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.Order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='origin_price',
            field=models.FloatField(verbose_name='original_price'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(verbose_name='order_price'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'shopping cart'), (11, 'submitted'), (12, 'paid'), (13, 'delivered'), (14, 'finished'), (15, 'deleted')], default=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modify_time'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='desc',
            field=models.CharField(max_length=256, verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='is_anonymous',
            field=models.BooleanField(default=True, verbose_name='anonymous_or_not'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='valid_or_not'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mine.Order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mall.Product', verbose_name='goods'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reorder',
            field=models.SmallIntegerField(default=0, verbose_name='sort'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='score',
            field=models.FloatField(default=10.0, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='score_deliver',
            field=models.FloatField(default=10.0, verbose_name='deliver_score'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='score_package',
            field=models.FloatField(default=10.0, verbose_name='service_score'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='score_speed',
            field=models.FloatField(default=10.0, verbose_name='speed_score'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update_time'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.User', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buy_amount',
            field=models.FloatField(verbose_name='total_price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buy_count',
            field=models.IntegerField(default=1, verbose_name='purchase_quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='express_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='order_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='express_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='express'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sn',
            field=models.CharField(max_length=32, verbose_name='order_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'shopping cart'), (11, 'submitted'), (12, 'paid'), (13, 'delivered'), (14, 'finished'), (15, 'deleted')], default=11, verbose_name='order_status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_address',
            field=models.CharField(max_length=256, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_area',
            field=models.CharField(max_length=32, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_phone',
            field=models.CharField(max_length=32, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_user',
            field=models.CharField(max_length=32, verbose_name='receiver'),
        ),
    ]
