# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-04 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passowrd',
            new_name='password',
        ),
    ]
