# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200523_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='username',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='recipient',
            field=models.CharField(default=1, max_length=32, verbose_name='recipient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='address',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='created_at',
            field=models.DateTimeField(verbose_name='login_time'),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='source',
            field=models.CharField(max_length=32, verbose_name='login_source'),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='username',
            field=models.CharField(max_length=64, verbose_name='login_account'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(max_length=256, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='area',
            field=models.CharField(max_length=32, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=32, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='default_address_or_not'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='valid_or_not'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='recipient_phone'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='province',
            field=models.CharField(max_length=32, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='town',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modify_time'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.SmallIntegerField(default=0, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_email_valid',
            field=models.BooleanField(default=False, verbose_name='email_valid_or_not'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_phone_valid',
            field=models.BooleanField(default=False, verbose_name='phone_valid_or_not'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(max_length=32, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (0, 'Female')], default=1, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modify_time'),
        ),
    ]
