# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-27 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190506_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='用户级别'),
        ),
    ]
